### ISSUE TITLE
<名簿班>データ格納方法の検討

### ISSUE THREAD

**Issue by TakahiroTsujiura** [enpit2016fun/minipbl_b#12]

**Comment by takhos1411** [comment]
Cordovaチュートリアルで使っているemployeeオブジェクトを参考に、localsrorageに格納することにする。
情報発信班とのインタフェースは、ParentServiceオブジェクトで行う。
NameListSampleでParentServiceオブジェクトへの具体的なアクセス方法をjs/app.jsで例示。
物理的な格納については、別途。
