### ISSUE TITLE
 <名簿班>データメンテナンス画面のデザインと実装

### ISSUE THREAD

**Issue by TakahiroTsujiura** [enpit2016fun/minipbl_b#13]

**Comment by takhos1411** [comment]
画面デザインおよび画面遷移を実施。
イメージは、以下の通り。（slackに上げてある）
[https://files.slack.com/files-pri/T10SK4D6J-F23UXP8DC/dsc_1233.jpg](url)

実装は、ラスカル新井が中心。

**Comment by takhos1411** [comment]
保護者の属性変更と新規追加が出来れば終了だと思う。
園児属性の変更、園児の新規追加画面は昨日の夜作った。（後で、プッシュ）

**Comment by m5201202** [comment]
おおよその実装が終わりpushしたことを確認したのでcloseします。
