### ISSUE TITLE
データベースの構成等を考える

### ISSUE THREAD

**Issue by TakahiroTsujiura** [enpit2016fun/minipbl_b#5]

**Comment by takhos1411** [comment]
メソッド間は、LocalStrageを使い、保護者（ｋｅｙ：ｐarent）,園児（key:cｈｉｌｄ)の情報を引き渡す。
JSON,parse,JSON.stringifyを使って、データ構造との変換を行う。
今回は、複数名がデータ更新（保護者の追加、園児の追加、保護者の属性変更）を行わないという前提。
プログラム終了時（データ更新時）には、ローカルファイルかgoogle storage上のファイルに書き出す。
プログラム開始時には、その逆で、ファイルからデータを読み込む。
