### ISSUE TITLE
使用するデータベースの検討とテスト

### ISSUE THREAD

**Issue by TakahiroTsujiura** [enpit2016fun/minipbl_b#8]

**Comment by takhos1411** [comment]
メモリ上でのデータ追加、データ変更のやり方は、サンプルコードの作成も含め終了。
後は、LocalStorageに格納したデータをファイルに書き出したり、その逆を行う確認をすればＯＫ．

**Comment by takhos1411** [comment]
ＰＨＰなどのサーバーサイドプログラムを使わない（今から使えるように調査する時間が無い）ので、Google SpreadSheetとの連携（ＡＰＩあり）を行うのが適当かと思ったが…。
そのためには、ＳｐｒｅａｄＳｈｅｅｔを公開しなければならないらしい。名簿情報を公開するのは、個人情報保護の観点から現実的ではない(昨日調べたみたが、使い方を把握できなかったこともある。　^_^; ）。よって、ちゃんと永続化を行うには、ＤＢＭＳを使う必要があると判断。
時間的制約があるので、今回のＭｉｎｉＰＢＬでは、ＬｏｃａｌＳｔｏｒａｇｅを使うところまでにする。（後学のために、明日、SpreadSheet連携を試してみる。）
ということで、このIssueはクローズ。
